title: Hopeless Programming
description: >-
    A chronicle of over-engineered masterpieces.
baseurl: /hopeless-programming
permalink: /hopeless-programming/:year/:month/:title/
theme: jekyll-theme-midnight

